index: 
    path: /
    controller: App\Controller\Web\DefaultController::index

app_login:
    path: /login
    controller: App\Controller\Web\SecurityController::login

app_logout:
    path: /logout

## AdminController



signup:
    path: /signup/{token}
    controller: App\Controller\Web\SecurityController::signup    

## OrganizationController
### API
postOrganization:
    path: /api/organization/post
    controller: App\Controller\API\OrganizationAPIController::postOrganization
 
putOrganization:
    path: /api/organization/put
    controller: App\Controller\API\OrganizationAPIController::putOrganization

getOrganization:
    path: /api/organization/get/
    controller: App\Controller\API\OrganizationAPIController::getOrganization  

deleteOrganization:
    path: /api/organization/delete/{orgName}
    controller: App\Controller\API\OrganizationAPIController::deleteOrganization
    

### WEB
organization:
    path: /web/organization
    controller: App\Controller\Web\OrganizationController::organization

## InviteController
### API
postInvite:
    path: /api/invite
    controller: App\Controller\API\InviteAPIController::postInvites

getInvites:
    path: /api/invite/get/organization
    controller: App\Controller\API\InviteAPIController::getInvites

deleteInvite:
    path: /api/invite/delete/{token}
    controller: App\Controller\API\InviteAPIController::deleteInvite
    
### WEB
invite:
    path: /web/invite
    controller: App\Controller\Web\InviteController::invite

## SecurityController
### API

