index: 
    path: /
    controller: App\Controller\WebController\DefaultController::index

app_login:
    path: /login
    controller: App\Controller\WebController\SecurityController::login

app_logout:
    path: /logout

signUp:
    path: /signup
    controller: App\Controller\WebController\SecurityController::signUp


## AdminController

createOrg:
    path: /admin/createOrg
    controller: App\Controller\WebController\AdminController::createOrg